from copy import deepcopy
from pathlib import Path
from tempfile import TemporaryDirectory
from threading import BoundedSemaphore
from types import SimpleNamespace
import subprocess

from sqlalchemy import select

from cognitive_os.application.recordings import get_recording, get_report, validate_sources
from cognitive_os.application.sessions import get_session
from cognitive_os.domain.errors import ApplicationError
from cognitive_os.infrastructure.database.models import Clarification
from cognitive_os.infrastructure.report_documents import build_document
from cognitive_os.infrastructure.storage.azure_recordings import recording_store
from cognitive_os.infrastructure.video import extract_frames
from cognitive_os.schemas.recordings import ReportResponse

# Bound video decoding and rendering per API process. Excess requests can retry explicitly.
EXPORT_SLOTS = BoundedSemaphore(2)


def export_snapshot(db, member, recording_id, revision):
    recording = get_recording(db, member, recording_id)
    # Writers of answers, reviews and regeneration take this same lock.
    get_session(db, member, recording.session_id, for_update=True)
    db.refresh(recording)
    report = get_report(db, member, recording_id)
    if recording.status != "ready":
        raise ApplicationError(409, "Wait for recording analysis to finish")
    if report.revision != revision:
        raise ApplicationError(409, "Report changed; reload the latest revision")
    if report.review_status == "rejected":
        raise ApplicationError(409, "Revise the rejected report before exporting")
    questions = db.scalars(select(Clarification).where(
        Clarification.organization_id == member.organization_id,
        Clarification.session_id == recording.session_id).order_by(Clarification.created_at, Clarification.id).limit(101)).all()
    if any(item.resolved_at is None or not item.answer for item in questions):
        raise ApplicationError(409, "Resolve pending clarifications before exporting")
    if len(questions) > 100 or sum(len(item.question) + len(item.answer) for item in questions) > 200_000:
        raise ApplicationError(413, "Clarifications exceed document export limit")
    snapshot = ReportResponse.model_validate(report).model_dump(mode="json")
    if not snapshot["content"]["instructions"]:
        raise ApplicationError(409, "Report has no activities to export")
    validate_sources(ReportResponse.model_validate(report).content, report.sampling)
    snapshot["clarifications"] = [{"question": item.question, "answer": item.answer} for item in questions]
    source = SimpleNamespace(**{key: getattr(recording, key) for key in
                               ("blob_key", "blob_snapshot", "size_bytes", "content_sha256", "media_type")})
    # The immutable value snapshot survives transaction release during storage and media work.
    db.rollback()
    return deepcopy(snapshot), source


def export_document(snapshot, recording, settings, *, format, style):
    if not EXPORT_SLOTS.acquire(blocking=False):
        raise ApplicationError(429, "Document exports are busy; retry shortly")
    try:
        with TemporaryDirectory(prefix="cognitive-export-") as directory:
            root = Path(directory)
            indices = {index for step in snapshot["content"]["instructions"] for index in step["frame_indices"]}
            frames = {}
            if indices:
                if not recording.blob_snapshot:
                    raise ApplicationError(409, "Recording snapshot is unavailable")
                with recording_store(settings) as store:
                    store.ensure_private()
                    store.download(recording, root / "recording")
                interval = snapshot["sampling"].get("frame_interval_seconds")
                if not isinstance(interval, int) or not 5 <= interval <= 60:
                    raise ApplicationError(409, "Recording sampling metadata is unavailable")
                sampled = extract_frames(root / "recording", root, recording.media_type,
                                         settings.model_copy(update={"recording_frame_interval_seconds": interval}))
                for index in indices:
                    original = snapshot["sampling"]["frames"][index]
                    if index >= len(sampled["frames"]) or sampled["frames"][index]["timestamp_ms"] != original["timestamp_ms"]:
                        raise ApplicationError(409, "Video captures no longer match the analyzed evidence")
                    # Filenames are generated by our decoder, never taken from report/model input.
                    frames[index] = (root / f"frame-{index:03d}.jpg", original["timestamp_ms"])
            target = root / f"document.{format}"
            build_document(snapshot, frames, target, style=style, format=format)
            if target.stat().st_size > 32 * 1024 * 1024:
                raise ApplicationError(413, "Document exceeds download limit")
            return target.read_bytes()
    except (subprocess.SubprocessError, ValueError, OSError):
        raise ApplicationError(503, "Document generation failed; verify the video and retry") from None
    finally:
        EXPORT_SLOTS.release()
